server:
  port: 9000

spring:
  threads:
    virtual:
      enabled: true
  config:
    import: vault://secret/gateway
  cloud:
    vault:
      host: vault
      port: 8200
      scheme: http
      token: root
      kv:
        enabled: true
  application:
    name: gateway